# Generated by Django 4.1 on 2022-09-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('IssueId', models.AutoField(primary_key=True, serialize=False)),
                ('IssueTitle', models.CharField(max_length=250)),
                ('IssueDescription', models.CharField(max_length=350)),
                ('IssueAssignee', models.CharField(max_length=150)),
                ('IssueReporter', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=250)),
                ('ProjectDescription', models.CharField(max_length=350)),
                ('ProjectAssignee', models.CharField(max_length=150)),
                ('ProjectReporter', models.CharField(max_length=150)),
            ],
        ),
    ]
